added wav2flac function

diff --git a/_functions b/_functions
--- a/_functions
+++ b/_functions
@@ -491,7 +491,7 @@ function steep {
 }
 
 # mov to gif
-function video_to_gif() {
+function vid2gif() {
   if ! [ -x "$(command -v ffmpeg)" ]; then
     echo 'Error: ffmpeg is not installed. please install with (brew install ffmpeg)' >&2
     exit 1
@@ -503,6 +503,16 @@ function video_to_gif() {
   fi
 
   ffmpeg -i "$1" -pix_fmt rgb24 -r 10 -f gif - | gifsicle --optimize=3 --delay=8 > ~/Downloads/"$1".gif
+}
+
+# wav to flac
+function wav2flac() {
+  if ! [ -x "$(command -v ffmpeg)" ]; then
+    echo 'Error: ffmpeg is not installed. please install with (brew install ffmpeg)' >&2
+    exit 1
+  fi
+
+  for i in *.wav; do ffmpeg -i "$i" "${i%.*}.flac"; done
 }
 
 ##############################################################
